project_name: spanner-console
archives:
 - id: default
   format: binary
builds:
  - env:
      - CGO_ENABLED=0
    ignore:
      - goos: linux
        goarch: 386    
      - goos: windows
      - goos: darwin
